export const tabledata = [
  {
    id: 1,
    categoria: "Usuário",
    acao: "alteracao",
    mensagem: "Treffy alterou o nome de SpanTaxota para Treffy.",
    descrição: "-",
    data: "37 segundos atras",
  },
  {
    id: 2,
    categoria: "Usuário",
    acao: "finalizacao",
    mensagem: "Treffy alterou o nome de SpanTaxota para Treffy.",
    descrição: "-",
    data: "37 segundos atras",
  },
  {
    id: 3,
    categoria: "Usuário",
    acao: "remocao",
    mensagem: "Treffy alterou o nome de SpanTaxota para Treffy.",
    descrição: "-",
    data: "37 segundos atras",
  },
  {
    id: 4,
    categoria: "Usuário",
    acao: "alteracao",
    mensagem: "Treffy alterou o nome de SpanTaxota para Treffy.",
    descrição: "-",
    data: "37 segundos atras",
  },
  {
    id: 5,
    categoria: "Usuário",
    acao: "criacao",
    mensagem: "Treffy alterou o nome de SpanTaxota para Treffy.",
    descrição: "-",
    data: "37 segundos atras",
  },
  {
    id: 6,
    categoria: "Usuário",
    acao: "alteracao",
    mensagem: "Treffy alterou o nome de SpanTaxota para Treffy.",
    descrição: "-",
    data: "37 segundos atras",
  },
]
