import { z } from "zod"

export const traitsEnum = z.enum([
  "Attack Speed",
  "Attack Range Increase",
  "Max Health",
  "Health Regen",
  "Max Mana",
  "Mana Regen",
  "Mana Cost Efficiency",
  "Melee Endurance",
  "Ranged Endurance",
  "Magic Endurance",
  "Melee Heavy Attack Evasion",
  "Ranged Heavy Attack Evasion",
  "Magic Heavy Attack Evasion",
  "Melee Evasion",
  "Ranged Evasion",
  "Magic Evasion",
  //
  "Boss Melee Critical Hit Chance",
  "Boss Ranged Critical Hit Chance",
  "Boss Magic Critical Hit Chance",
  "Boss Melee Endurance",
  "Boss Ranged Endurance",
  "Boss Magic Endurance",
  "Boss Melee Heavy Attack Chance",
  "Boss Ranged Heavy Attack Chance",
  "Boss Magic Heavy Attack Chance",
  "Boss Melee Heavy Attack Evasion",
  "Boss Ranged Heavy Attack Evasion",
  "Boss Magic Heavy Attack Evasion",
  "Boss Melee Hit Chance",
  "Boss Ranged Hit Chance",
  "Boss Magic Hit Chance",
  "Boss Melee Evasion",
  "Boss Ranged Evasion",
  "Boss Magic Evasion",
  //
  "PvP Melee Critical Hit Chance",
  "PvP Ranged Critical Hit Chance",
  "PvP Magic Critical Hit Chance",
  "PvP Melee Endurance",
  "PvP Ranged Endurance",
  "PvP Magic Endurance",
  "PvP Melee Heavy Attack Chance",
  "PvP Ranged Heavy Attack Chance",
  "PvP Magic Heavy Attack Chance",
  "PvP Melee Heavy Attack Evasion",
  "PvP Ranged Heavy Attack Evasion",
  "PvP Magic Heavy Attack Evasion",
  "PvP Melee Hit Chance",
  "PvP Ranged Hit Chance",
  "PvP Magic Hit Chance",
  "PvP Melee Evasion",
  "PvP Ranged Evasion",
  "PvP Magic Evasion",
  //
  "Skill Damage Boost",
  "Skill Damage Resistance",
  "Buff Duration",
  "Debuff Duration",
  //
  "Humanoid Damage Reduction",
  "Humanoid Boost Damage",
  "Demon Damage Reduction",
  "Demon Boost Damage",
  "Undead Damage Reduction",
  "Undead Boost Damage",
  "Construct Damage Reduction",
  "Construct Boost Damage",
  "Wildkin Damage Reduction",
  "Wildkin Boost Damage",
  //
  "Weaken Chance",
  "Weaken Resistance",
  "Stun Chance",
  "Stun Resistance",
  "Petrification Chance",
  "Petrification Resistance",
  "Sleep Chance",
  "Sleep Resistance",
  "Silence Chance",
  "Silence Resistance",
  "Bind Chance",
  "Bind Resistance",
  "Fear Chance",
  "Fear Resistance",
  //
  "Amitoi Healing",
  "Evasion",
  "Endurance",
  //
  "Melee Defense",
  "Ranged Defense",
  "Magic Defense",
  //
  "Critical Hit Chance",
  "Melee Critical Hit Chance",
  "Ranged Critical Hit Chance",
  "Magic Critical Hit Chance",
  "Melee Heavy Attack Chance",
  "Ranged Heavy Attack Chance",
  "Magic Heavy Attack Chance",
  //
  "Hit Chance",
  "Melee Hit Chance",
  "Ranged Hit Chance",
  "Magic Hit Chance",
  //
  "Sem Trait",
])
