import type { Metadata } from "next"
import { Poppins } from "next/font/google"

import NextAuthProvider from "./_providers/NextAuthProvider"
import QueryClientProvider from "./_providers/QueryClientProvider"
import { cn } from "@/lib/utils"
import "./globals.css"

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          poppins.className,
          "flex h-screen flex-col items-center gap-12 bg-neutral-900"
        )}
      >
        <NextAuthProvider>
          <QueryClientProvider>{children}</QueryClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
